use super::helpers::SecretString;
use l2_core::Hash32;
use std::net::IpAddr;
use std::net::SocketAddr;
use std::path::PathBuf;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TonNetwork {
    Testnet,
}

#[derive(Clone, Eq, PartialEq)]
pub struct NodeConfig {
    pub l2_name: String,
    pub chain_id: String,
    pub native_token_name: String,
    pub native_token_symbol: String,
    pub node_addr: SocketAddr,
    pub ton_network: TonNetwork,
    pub toncenter_v3_base_url: String,
    pub toncenter_api_key: SecretString,
    pub tonapi_base_url: String,
    pub tonapi_key: SecretString,
    pub database_url: SecretString,
    pub redis_url: SecretString,
    pub admin_token: SecretString,
    pub challenge_window_sec: u32,
    pub ent_faucet_amount: u128,
    pub ent_faucet_max_amount: u128,
    pub ent_decimals: u8,
    pub ent_logo_path: PathBuf,
    pub ent_faucet_require_admin: bool,
    pub l1_deposit_indexer_enabled: bool,
    pub l1_vault_address: Option<String>,
    pub l1_deposit_poll_interval_ms: u64,
    pub l1_deposit_batch_limit: u16,
    pub l1_deposit_confirmation_lag_lt: u64,
    pub l1_ton_asset_id: u32,
    pub l1_deposit_asset_ids: Vec<u32>,
    pub dev_admin_deposits_enabled: bool,
    pub l1_batch_relayer_enabled: bool,
    pub l1_rollup_root_address: Option<String>,
    pub l1_sequencer_sender_address: Option<String>,
    pub l1_commit_signer_endpoint: Option<String>,
    pub l1_commit_signer_token: Option<SecretString>,
    pub l1_commit_msg_value_nanoton: u64,
    pub l1_batch_relayer_poll_interval_ms: u64,
    pub l1_batch_relayer_retry_backoff_ms: u64,
    pub l1_batch_relayer_max_attempts: u32,
    pub l1_batch_finalizer_enabled: bool,
    pub l1_finalize_signer_endpoint: Option<String>,
    pub l1_finalize_signer_token: Option<SecretString>,
    pub l1_finalize_msg_value_nanoton: u64,
    pub l1_batch_finalizer_poll_interval_ms: u64,
    pub l1_batch_finalizer_retry_backoff_ms: u64,
    pub l1_batch_finalizer_max_attempts: u32,
    pub da_max_payload_bytes: usize,
    pub da_public_backend: String,
    pub da_public_fs_dir: PathBuf,
    pub da_public_base_url: Option<String>,
    pub tvm_adapter: l2_core::TvmAdapterMode,
    pub tvm_tonlib_library_path: Option<PathBuf>,
    pub tvm_getter_default_gas_limit: u64,
    pub tvm_getter_max_gas_limit: u64,
    pub tvm_getter_timeout_ms: u64,
    pub tvm_getter_max_stack_boc_bytes: usize,
    pub internal_queue_max_len: usize,
    pub internal_queue_max_per_block: usize,
    pub internal_message_gas_limit: u64,
    pub mempool_replay_ttl_secs: u64,
    pub mempool_nonce_lock_ttl_secs: u64,
    pub mempool_leader_ttl_secs: u64,
    pub mempool_rate_limit_window_secs: u64,
    pub mempool_ip_rate_limit_window_secs: u64,
    pub mempool_max_global_queue: usize,
    pub mempool_max_account_queue: usize,
    pub mempool_max_account_nonce_window: u64,
    pub mempool_max_account_submissions_per_window: u32,
    pub mempool_max_ip_submissions_per_window: u32,
    pub mempool_max_payload_bytes: usize,
    pub mempool_max_transfer_payload_bytes: usize,
    pub mempool_max_withdraw_payload_bytes: usize,
    pub mempool_max_call_payload_bytes: usize,
    pub mempool_max_deploy_payload_bytes: usize,
    pub mempool_max_call_body_boc_base64_bytes: usize,
    pub mempool_min_gas_limit: u64,
    pub mempool_max_gas_limit: u64,
    pub mempool_min_gas_price: u128,
    pub mempool_max_tx_fee: u128,
    pub mempool_pop_batch_size: usize,
    pub mempool_banned_ips: Vec<IpAddr>,
    pub mempool_banned_accounts: Vec<Hash32>,
    pub executor_gas_schedule: l2_core::GasSchedule,
}
